### ISSUE TITLE
package.json hardcoded directory paths

### ISSUE THREAD

**Issue by nikopolv** [dlucidone/nativescript-calendar-weekview#2]
The Demo folder's package.json has a few hard coded paths that make it impossible to run and test the demo.

**Comment by dlucidone** [comment]
@nikopolv Yes, I missed it, Are you able to run the plugin or not?

**Comment by nikopolv** [comment]
I can run the plugin as a part of my own project but the demo project of this repository won't run.

It would help a lot if we would be able to run the demo. We could give a hand with the development and send you pull requests :)

**Comment by dlucidone** [comment]
@nikopolv I'll Update It.Thanks
